name: 'Cross-OS Test'
on:
  schedule:
    - cron:  '0 2 * * *' # UTC time

defaults:
  run:
    shell: bash

jobs:
  test-e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    env:
      VUE_APP_BACKEND_TYPE: 'testVolatile'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}" >> .npmrc
      name: add auth token for npm packages
    - run: npm ci
    - run: npm run build
    - uses: nick-invision/retry@v2
      name: End-To-End tests on ${{ matrix.os }} w/ local backend
      with:
        timeout_minutes: 20
        max_attempts: 3
        command: npm run test:e2e:run
