name: devradar-push

on:
  push:
    paths:
      - 'app/**'
      - '.github/**'

jobs:
  test-lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
      working-directory: app
    - run: |
        npm run lint
        npm run build
      name: check for lint and tsc errors
      working-directory: app

  test-e2e-volatile:
    runs-on: ubuntu-18.04
    env:
      VUE_APP_BACKEND_TYPE: 'testVolatile'
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
      working-directory: app
    - run: |
        npm run build
        npm run test:e2e:run
      name: cypress tests w/ local storage
      working-directory: app

  firebase-deploy:
    name: "publish devradar.io"
    #if: github.event_name == 'push' && github.ref == 'refs/heads/master' # YOLO deployments
    needs: [test-lint, test-e2e-volatile]
    runs-on: ubuntu-latest
    env:
      VUE_APP_BACKEND_TYPE: 'firebase'
      VUE_APP_BACKEND_PROJECT: ${{ secrets.FIREBASE_DAAS_PROJECT }}
      VUE_APP_BACKEND_KEY: ${{ secrets.FIREBASE_DAAS_CLIENTKEY }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: |
        cd app
        npm ci
        npm run build
      name: build
    - run: |
        cd app
        npm i -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_DAAS_TOKEN }} --project ${{ secrets.FIREBASE_DAAS_PROJECT }}
      name: deploy to firebase
