name: devradar.io - PR

on: [pull_request]

defaults:
  run:
    shell: bash

jobs:
  test-lint-eslint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}" >> .npmrc
      name: add auth token for npm packages
    - run: npm ci
    - run: npm run lint
      name: eslint/standard

  test-lint-tsc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}" >> .npmrc
      name: add auth token for npm packages
    - run: npm ci
    - run: npm run build
      name: tsc build

  test-e2e-volatile:
    runs-on: ubuntu-18.04
    env:
      VUE_APP_BACKEND_TYPE: 'testVolatile'
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}" >> .npmrc
      name: add auth token for npm packages
    - run: npm ci
    - run: |
        npm run build
        npm run test:e2e:run
      name: cypress tests w/ local storage

  test-e2e-firebase:
    runs-on: ubuntu-18.04
    env:
      VUE_APP_BACKEND_TYPE: 'firebase'
      VUE_APP_BACKEND_PROJECT: ${{ secrets.FIREBASE_E2E_PROJECT }}
      VUE_APP_BACKEND_KEY: ${{ secrets.FIREBASE_E2E_CLIENTKEY }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
      FIREBASE_SERVICEACCOUNT: ${{ secrets.FIREBASE_E2E_ACCOUNTKEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}" >> .npmrc
      name: add auth token for npm packages
    - run: npm ci
    - run: npm run build
    - run: |
        npm run test:e2e:run
        # npm run test:e2e:ci:firebase:record # cypress key provided via CYPRESS_RECORD_KEY env variable
      name: cypress tests w/ firebase backend
